[package]
name = "scoring"
authors = ["Evgeniy Terekhin <e_terekhin@pm.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
csv = "1"
eyre = "0.6"

[dev-dependencies]
assert_matches = "1"
pretty_assertions = "1"
